### ISSUE TITLE
not work with cnblogs plugins

### ISSUE THREAD

**Issue by zhaoqingqing** [LiarOnce/MarkdownInLiveWriter#1]
hi, i also install a cnblogs plugins ：http://www.cnblogs.com/zsy/p/5859928.html
and install you plugins. restart olw later , only enable cnblogs plugins ,markdown not see.
![image](https://cloud.githubusercontent.com/assets/3056814/25415230/fcc45fa4-2a68-11e7-908f-676859dd6f75.png)
![image](https://cloud.githubusercontent.com/assets/3056814/25415234/02755656-2a69-11e7-96a6-d8724ffe3a70.png)

**Comment by LiarOnce** [comment]
You need to restart Open Live Writer.
It works well in my computer.
![snipaste_20170426_121221.png](https://ooo.0o0.ooo/2017/04/26/59001e546f76d.png)
Did you install .NET Framework 4.5.1 or later?

**Comment by zhaoqingqing** [comment]
@LiarOnce  restart olw ,and have .net 4.5.1 . my os is windows 7 x64

**Comment by LiarOnce** [comment]
@zhaoqingqing  Can you upload the log of Open Live Writer?（你可以上传OLW的日志吗？）
This file is located in （这个文件位于）C:\Users\(your username)\AppData\Local\OpenLiveWriter\OpenLiveWriter.log
I only need the most recently used record instead of all.（我只需要最近使用的记录而不是全部。）

**Comment by zhaoqingqing** [comment]
@LiarOnce 
[Open Live Writer.log.txt](https://github.com/LiarOnce/MarkdownInLiveWriter/files/992397/Open.Live.Writer.log.txt)

**Comment by LiarOnce** [comment]
@zhaoqingqing 
Sorry, I did not specify in README.md that this plugin requires .NET Framework 4.5.2 or later.

**Comment by xianshenglu** [comment]
I got the same problem with  .NET Framework 4.6.1

**Comment by LiarOnce** [comment]
@xianshenglu You can confirm if it has been removed by the antivirus software. (e.g. Windows Defender)

**Comment by xianshenglu** [comment]
[Open Live Writer.log](https://github.com/LiarOnce/MarkdownInLiveWriter/files/1951243/Open.Live.Writer.log)

**Comment by xianshenglu** [comment]
guess this will help.It is not removed by kingsoft

**Comment by xianshenglu** [comment]
I will keep searching information and try to fix it

**Comment by LiarOnce** [comment]
@xianshenglu 
You can try adding these in the `<runtime>` tag in the` OpenLiveWriter.exe.config` file:
```xml
<loadFromRemoteSources enabled="true"/>
```
Example:
```xml
<configuration>
<runtime>
    <loadFromRemoteSources enabled="true"/>
</runtime>
</configuration>
```

**Comment by xianshenglu** [comment]
thanks so much

**Comment by xianshenglu** [comment]
It works.Actually i find [answer](https://stackoverflow.com/questions/8524423/could-not-load-file-or-assembly-hresult-0x80131515-when-adding-controller-to-m) in so.But I didn't solve it .Anyway,thanks .
